### ISSUE TITLE
Does this support multi process?

### ISSUE THREAD

**Issue by printfinn** [iSOLveIT/sphinx-pdf-generate#1]
Sphinx has a `-j` option, that allows you to use multi processing to speed up documentation build.

I tried `sphinx-pdf-generate docs/source docs/build/html -E -a -j 8 `, the reading source and copy downloadable files process are as fast as they used to be like `sphinx-build -b html docs/source/ docs/build/html -j 8`, but only one PDF is generated. 

```text
[sphinx-pdf-generate] Converting Displays/PIM-101-C.rst to PIM-101-C.pdf
[sphinx-pdf-generate] Skipped: PDF conversion for genindex.rst
[sphinx-pdf-generate] Skipped: PDF conversion for search.rst
[sphinx-pdf-generate] Converting 1 file(s) to PDF took 6.7s
```

I was thinking all 10 PDFs should be generated, and 100+ skipped.

----

Can we gen PDF in multi processes/threads? Or can I build doc in multi process, and then manually only trigger the gen PDF job?

Sometimes I might only want to gen a single PDF to see how it looks like, do we have a CLI option to only gen one single PDF for one RST file? Because gen all PDFs is slow, 10 PDFs take like 40 seconds on a M1 Mac.

Thanks!

**Comment by iSOLveIT** [comment]
> Sphinx has a `-j` option, that allows you to use multi processing to speed up documentation build.
> 
> I tried `sphinx-pdf-generate docs/source docs/build/html -E -a -j 8 `, the reading source and copy downloadable files process are as fast as they used to be like `sphinx-build -b html docs/source/ docs/build/html -j 8`, but only one PDF is generated.

First of all, any Sphinx build option (e.g. `-j` ) you pass to the `sphinx-pdf-generate` CLI is passed to Sphinx when building the docs. So the command you used, `sphinx-pdf-generate -a -E -j 8 docs/source docs/_build/html` should generate all the 10 PDFs. 
But from what I realised, if you pass the `-j 8` option which enables parallel build, `sphinx-pdf-generate` won't be able to gather all the information needed to build PDF files. You can check the `pdf_metadata.json` file in OUTPUTDIR to see the difference between when you use `-j` and when you don't.

> Sometimes I might only want to gen a single PDF to see how it looks like, do we have a CLI option to only gen one single PDF for one RST file? Because gen all PDFs is slow, 10 PDFs take like 40 seconds on a M1 Mac.

Although you can generate PDF files for entire docs projects, it is not recommended to do that if you have thousands of RST files. This is because the underlining PDF generation package (i.e. **weasyprint**) is slow.
It is best to use the  `pdfgen_debug`  and `pdfgen_debug_target` options to generate a single PDF file to see what it looks like.

The `pdfgen_debug` option allows you to debug the entire PDF generation process but if you want to target a specific RST file or you want to generate a single PDF to see what it looks like then you must set the `pdfgen_debug_target` option as well. 
The `pdfgen_debug_target` option takes the path to an RST file as its value. With both the `pdfgen_debug` and `pdfgen_debug_target` options set, you can generate a single PDF of the target file to see what it looks like.

You can read more about the [pdfgen_debug option](https://isolveit.github.io/sphinx-pdf-generate/options.html#pdfgen-debug-for-development-purposes-only) and [pdfgen_debug_target option](https://isolveit.github.io/sphinx-pdf-generate/options.html#pdfgen-debug-target-for-development-purposes-only).

> Can we gen PDF in multi processes/threads? Or can I build doc in multi process, and then manually only trigger the gen PDF job?

Regarding whether we can generate PDFs in multi processes/threads, the answer is no because the underlying package (i.e. **weasyprint**) we use for converting the HTML build files to PDF doesn't allow that. Also, you can't trigger the gen PDF job manually since it needs certain data from the `sphinx-build` process.

I will need to look through the multi-process/parallel build problem further to debug the issue. 
Kindly, let me know if you encounter any issues. Thanks for raising the issue 👍🏽.

**Comment by printfinn** [comment]
Thanks Randy! I'm now able to debug only one pdf at a time!
I'll take a look at weasyprint to see if there is anything I can do to speed up the process.
Thank you!

**Comment by iSOLveIT** [comment]
Welcome. And kindly let me know when you come with a solution for weasyprint.
